{% set name = "google-api-python-client" %}
{% set version = "2.52.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0ae3fa7cad2102e24a587986cee53afdbc95bd69b58f2c08f8fd881a20da5f14

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core >=1.31.5,<3.0.0dev,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - google-auth >=1.16.0,<3.0.0dev
    - google-auth-httplib2 >=0.1.0
    - httplib2 >=0.15.0,<1dev
    - uritemplate >=3.0.1,<5

test:
  imports:
    - apiclient
    - googleapiclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache-2.0 and MIT
  license_file: LICENSE
  summary: Google API Client Library for Python
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - xylar
    - akrherz
    - ocefpaf
