{% set name = "google-api-python-client" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9879b8d1d18212ae92b35bab61e8ea9ed5ea63ef9c8ca847938538da10dd193b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core >=1.21.0,<2dev
    - google-auth >=1.16.0,<2dev
    - google-auth-httplib2 >=0.1.0
    - httplib2 >=0.15.0,<1dev
    - six >=1.13.0,<2dev
    - uritemplate >=3.0.0,<4dev

test:
  imports:
    - apiclient
    - googleapiclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache-2.0 and MIT
  license_file: LICENSE
  summary: Google API Client Library for Python
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
