{% set name = "google-api-python-client" %}
{% set version = "2.117.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/google-api-python-client-{{ version }}.tar.gz
  sha256: b38cd1477ee3c341a0d2f7427326499b416f36c44e9b20d1da229df8be0c596e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - httplib2 >=0.15.0,<1.dev0
    - google-auth >=1.19.0,<3.0.0.dev0
    - google-auth-httplib2 >=0.1.0
    - google-api-core >=1.31.5,<3.0.0.dev0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - uritemplate >=3.0.1,<5

test:
  imports:
    - apiclient
    - googleapiclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache-2.0 and MIT
  license_file: LICENSE
  summary: Google API Client Library for Python
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - xylar
    - akrherz
    - ocefpaf
