{% set name = "google-api-python-client" %}
{% set version = "2.151.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/google_api_python_client-{{ version }}.tar.gz
  sha256: a9d26d630810ed4631aea21d1de3e42072f98240aaf184a8a1a874a371115034

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - httplib2 >=0.19.0,<1.dev0
    - google-auth >=1.32.0,<3.0.0.dev0,!=2.24.0,!=2.25.0
    - google-auth-httplib2 >=0.2.0,<1.0.0
    - google-api-core >=1.31.5,<3.0.0.dev0,!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.0
    - uritemplate >=3.0.1,<5

test:
  imports:
    - apiclient
    - googleapiclient
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/google/google-api-python-client/
  license: Apache-2.0 and MIT
  license_file: LICENSE
  summary: Google API Client Library for Python
  dev_url: https://github.com/google/google-api-python-client/
  doc_url: https://developers.google.com/api-client-library/python/start/get_started

extra:
  recipe-maintainers:
    - xylar
    - akrherz
    - ocefpaf
